// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDq6I67bIeMu9Tz0ZVGPCRgR8kCxNr5vM4',
    appId: '1:748963462808:web:e00984be6cab10f546daed',
    messagingSenderId: '748963462808',
    projectId: 'fir-flutter-codelab-11801',
    authDomain: 'fir-flutter-codelab-11801.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-11801.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2cOUM6EqMK_Q4jkNtUrMCXnn3uFHolFU',
    appId: '1:748963462808:android:c4d62b473644605746daed',
    messagingSenderId: '748963462808',
    projectId: 'fir-flutter-codelab-11801',
    storageBucket: 'fir-flutter-codelab-11801.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBjwERp1VAGlA1QFcAakaPH5T6h78IZYE',
    appId: '1:748963462808:ios:470f79fdb15fb82646daed',
    messagingSenderId: '748963462808',
    projectId: 'fir-flutter-codelab-11801',
    storageBucket: 'fir-flutter-codelab-11801.appspot.com',
    iosClientId: '748963462808-4re09s7bd390v3folpcsur6v6jfhngjf.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBjwERp1VAGlA1QFcAakaPH5T6h78IZYE',
    appId: '1:748963462808:ios:470f79fdb15fb82646daed',
    messagingSenderId: '748963462808',
    projectId: 'fir-flutter-codelab-11801',
    storageBucket: 'fir-flutter-codelab-11801.appspot.com',
    iosClientId: '748963462808-4re09s7bd390v3folpcsur6v6jfhngjf.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
